### ISSUE TITLE
‘imsplit’ missing

### ISSUE THREAD

**Issue by BrainPotter** [vitorsr/SIHR#1]
dear vitorsr ,when I ran this program on my computer,I got the following error:
main
未定义函数或变量 'imsplit'。

出错 zSpecularFreeImage (line 4)
[r,g,b] = imsplit(src.rgb);

出错 zRemoveHighlights (line 2)
[src,sfi] = zSpecularFreeImage(img);

出错 zHighlightRemoval (line 5)
[sfi,diff] = zRemoveHighlights(img);

出错 main (line 2)
[img,sfi,diff] = zHighlightRemoval(fname,[NaN 128]);
Is there a function or variable called ‘imsplit’ missing？
I‘m looking forward to your reply，Thank you very much！

**Comment by vitorsr** [comment]
Hello Internet friend, I'm sorry for the late reply (I didn't receive a notification)!

`imsplit` is a MATLAB function from the R2018b [Image Processing Toolbox](https://www.mathworks.com/products/image.html), you could be missing it in your MATLAB installation or have an earlier version.

Can you verify if you have it or not by running
`>> ver`
on your MATLAB console?

P.S. I made some changes to the code, main is now located in z, you can call it using
```[src,sfi,diff] = z.main(fname,sz)```, fname is path to an image and sz is the size argument from `imresize`, can be a scale value or in [nRow,nCol] format.
