### ISSUE TITLE
Improved documentation of API?

### ISSUE THREAD

**Issue by thomakra** [vitorsr/SIHR#10]
The basic interface is well described in the documentation as `I_d = AuthorYEAR(I);`, but a few of the methods seem to output two components (Akashi2016, and Shen2013).

It might be nice to document what the extra component is?
If J_s and I_s represent the specular component, why is it given as an extra output?
Is this different than what I would get if I did ` I_s = I - I_d;`?

**Comment by vitorsr** [comment]
> Is this different than what I would get if I did I_s = I - I_d;

I've looked into it. No, it's not any different, hence the same nomenclature.

I'll remove the extra output for consistency. 😄
