### ISSUE TITLE
journal paper of [12]

### ISSUE THREAD

**Issue by achiton** [vitorsr/SIHR#4]
Hello, 
Thank you for your excellent works about implementing separation methods.
Very interesting and useful!

I found the journal paper of [12] "Efficient improvement method for separation of reflection components based on an energy function".
URL is as follows.
https://www.jstage.jst.go.jp/article/mta/7/2/7_92/_article/-char/en

Please refer and use this.
Thank you.

**Comment by vitorsr** [comment]
Hi! Thanks for noticing. I was aware of the paper but forgot to update the references and script in this repository.

I read the journal paper and it is much more clarifying than the conference paper. The method is the same, but the journal paper introduces new parametrizations (cf. Table 1 and search area in Part 4, the SVD portion in Part 2 is unnecessary in my view).

Anyways, I will get to it soon and make the changes (been very busy this semester with other university duties 😩).

In the meantime, feel free to propose necessary changes that need to be made in the script – either here or through a pull request. I can help solve any doubts if you choose to make the changes yourself!

Cheers.

**Comment by achiton** [comment]
Hello.
Thank you for your quick response and opinion about the journal.
I will use your excellent codes to study the separation of reflection components.
Cheers!

**Comment by vitorsr** [comment]
Hi @achiton, I am updating the Yamamoto and Nakazawa improvement. Do you have any insights you'd like to share or any comments?

**Comment by vitorsr** [comment]
Done it! 😀

**Comment by achiton** [comment]
Hi vitorsr,

Thank you for updating the reference information and your good works about the implementations.
I have no comments about them.

Now, I'm pending my work about the separation of reflection components, but I will resume the work in the future. At that time, I will use your programs to study.

Thank you.
