### ISSUE TITLE
Tan2005 not working in Octave because newline is not supported

### ISSUE THREAD

**Issue by thomakra** [vitorsr/SIHR#8]
I tried to run the `Tan2005` method with Octave, but it fails because `newline` is not supported by Octave.

	octave:28> J_d = Tan2005(J);
	warning: the 'newline' function is not yet implemented in Octave

	Please read <https://www.octave.org/missing.html> to learn how you can
	contribute missing functionality.
	error: 'newline' undefined near line 25 column 53
	error: called from
	    Tan2005 at line 25 column 1
	octave:28> version
	ans = 4.4.1

**Comment by thomakra** [comment]
Sorry, I didn't see that you've tested it with Octave 5.1. I'll try to upgrade on my Ubuntu machine and see if it works.

**Comment by vitorsr** [comment]
I'll fix it, it's just a matter of changing `newline` to `sprintf('\n')`. Meanwhile, I'll test it on my Ubuntu VM.

Also, while I think the `apt` version lags behind the latest release, `newline` still isn't defined in the latest Octave, so... my mistake!

Did you manage to install [`image`](https://octave.sourceforge.io/image/index.html) from Octave Forge? I think Octave asks for `liboctave-dev` (needs to install separately via `apt`).

**Comment by thomakra** [comment]
Yes, I had to install liboctave-dev.
It would be nice to get that into the installation instructions.

Would you like me to put that in a separate issue?

**Comment by vitorsr** [comment]
Thanks for the feedback. I'll push it in the next commit - which should be soon. Any additional notes regarding the core [`README.md`](../blob/master/README.md)?

Right now, I'm waiting for the `my_quality` test script (performance reports of all methods) to finish, so I can validate Octave functionality.

`Tan2005` takes 2 minutes on MATLAB, but on Octave it seems to take close to an hour!

**Comment by thomakra** [comment]
Nice.
I've added a couple of issues with suggestions which I think would help.

Thanks.
